# Notebook Imports

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# Constants

In [5]:
TOKEN_SPAM_PROB_FILE = 'Data/SpamData/03_Testing/prob-spam.txt'
TOKEN_HAM_PROB_FILE = 'Data/SpamData/03_Testing/prob-nonspam.txt'
TOKEN_ALL_PROB_FILE = 'Data/SpamData/03_Testing/prob-all-tokens.txt'

TEST_FEATURES_FILE = 'Data/SpamData/03_Testing/test-features.txt'
TEST_TARGET_FILE = 'Data/SpamData/03_Testing/test-target.txt'

VOCAB_SIZE = 2500

# Load the Data

In [6]:
# Features
X_test = np.loadtxt(TEST_FEATURES_FILE, delimiter=' ')
# Target
y_test = np.loadtxt(TEST_TARGET_FILE, delimiter=' ')
# Token Probabilities
prob_token_spam = np.loadtxt(TOKEN_SPAM_PROB_FILE, delimiter=' ')
prob_token_ham = np.loadtxt(TOKEN_HAM_PROB_FILE, delimiter=' ')
prob_all_tokens = np.loadtxt(TOKEN_ALL_PROB_FILE, delimiter=' ')

# Joint Probability

In [7]:
X_test

array([[0., 0., 1., ..., 0., 0., 0.],
       [6., 1., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 4., 0., ..., 0., 0., 0.],
       [2., 2., 0., ..., 0., 0., 0.],
       [1., 9., 1., ..., 0., 0., 0.]])

In [8]:
prob_token_spam

array([1.20169352e-02, 5.16667495e-03, 6.73434128e-03, ...,
       9.93591336e-05, 1.37998797e-04, 5.51995187e-06])

In [10]:
X_test.dot(prob_token_spam).shape

(1724,)

## Set the Prior

$$P(Spam \, | \, X) = \frac{P(X \, | \, Spam) \, P(Spam)} {P(X)} $$

In [16]:
PROB_SPAM = 0.3116

Giờ ta sẽ dùng giá trị log để tính để chỉ phải dùng + và -, Ngoài ra còn giúp tính chuẩn hơn các chữ số thập phân

## Joint probability in log format

In [18]:
joint_log_spam = X_test.dot(np.log(prob_token_spam) - np.log(prob_all_tokens)) + np.log(PROB_SPAM)

In [20]:
joint_log_spam

array([  22.35846718,    1.96513912,   17.80956624, ..., -365.60976946,
        -10.09141566, -110.83239606])

$$P(Ham \, | \, X) = \frac{P(X \, | \, Ham) \,( 1 - P(Spam))} {P(X)} $$

In [19]:
joint_log_ham = X_test.dot(np.log(prob_token_ham) - np.log(prob_all_tokens)) + np.log(1- PROB_SPAM)

In [21]:
joint_log_ham

array([-58.94531635, -10.85583562, -34.75361709, ...,  59.97461553,
         0.06055575,  24.68662802])

In [22]:
joint_log_ham.size

1724

# Making Predictionsssssssss ( ͡° ͜ʖ ͡°)

### Checking for the higher joint probability
$$ P(Spam \, | \, X) > P(Ham\,|\,X) $$
<br>
<center>
**OR**
</center>
<br>
$$ P(Spam \, | \, X) < P(Ham\,|\,X) $$

In [25]:
prediction

array([1, 1, 1, ..., 0, 0, 0])