# Notebook Imports

In [1]:
import numpy as np
import pandas as pd

#  Constants

In [2]:
TRAINING_DATA_FILE = 'Data/SpamData/02_Training/train-data.txt'
TEST_DATA_FILE = 'Data/SpamData/02_Training/test-data.txt'

TOKEN_SPAM_PROB_FILE = 'Data/SpamData/03_Testing/prob-spam.txt'
TOKEN_HAM_PROB_FILE = 'Data/SpamData/03_Testing/prob-nonspam.txt'
TOKEN_ALL_PROB_FILE = 'Data/SpamData/03_Testing/prob-all-tokens.txt'

TEST_FEATURES_FILE = 'Data/SpamData/03_Testing/test-features.txt'
TEST_TARGET_FILE = 'Data/SpamData/03_Testing/test-target.txt'

VOCAB_SIZE = 2500

# Read and Load Features from .txt Files into Numpy Array

In [3]:
sparse_train_data = np.loadtxt(TRAINING_DATA_FILE, delimiter=' ', dtype=int)

In [4]:
sparse_test_data = np.loadtxt(TEST_DATA_FILE, delimiter=' ', dtype=int)

In [5]:
sparse_train_data[:5]

array([[ 0,  2,  1,  1],
       [ 0,  3,  1,  2],
       [ 0,  4,  1,  1],
       [ 0,  7,  1,  3],
       [ 0, 11,  1,  1]])

In [6]:
sparse_train_data[-5:]

array([[5795, 2047,    0,    1],
       [5795, 2055,    0,    2],
       [5795, 2301,    0,    1],
       [5795, 2349,    0,    1],
       [5795, 2439,    0,    1]])

In [7]:
print('Nr of rows in training file', sparse_train_data.shape[0])
print('Nr of rows in test file', sparse_test_data.shape[0])

Nr of rows in training file 258352
Nr of rows in test file 117625


In [8]:
sparse_train_data[:, 0] # first column

array([   0,    0,    0, ..., 5795, 5795, 5795])

In [9]:
print('Nr of emails in the training file', np.unique(sparse_train_data[:, 0]).shape[0])

Nr of emails in the training file 4015


### Create an Empty DataFrame

In [10]:
column_names = ['DOC_ID'] + ['CATEGORY'] + list(range(0, VOCAB_SIZE))
column_names[:5]

['DOC_ID', 'CATEGORY', 0, 1, 2]

In [11]:
index_names = np.unique(sparse_train_data[:, 0])
index_names

array([   0,    1,    2, ..., 5791, 5794, 5795])

In [12]:
full_train_data = pd.DataFrame(columns=column_names, index=index_names)
full_train_data

DOC_ID CATEGORY    0    1    2    3    4    5    6    7  ... 2490 2491  \
0       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
1       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
2       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
3       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
4       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
...     ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
5789    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5790    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5791    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5794    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5795    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   

     2492 2493 2494 2495 2496 2497 2498 2499  
0     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
3     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
...   ...  ...  ...  ...  ...  ...  ...  ...  
5789  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5790  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5791  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5794  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5795  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[4015 rows x 2502 columns]

In [13]:
full_train_data.fillna(value=0, inplace=True)
full_train_data

DOC_ID  CATEGORY  0  1  2  3  4  5  6  7  ...  2490  2491  2492  2493  \
0          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
1          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
...      ...       ... .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   
5789       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5790       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5791       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5794       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5795       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

      2494  2495  2496  2497  2498  2499  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     0     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
5789     0     0     0     0     0     0  
5790     0     0     0     0     0     0  
5791     0     0     0     0     0     0  
5794     0     0     0     0     0     0  
5795     0     0     0     0     0     0  

[4015 rows x 2502 columns]

# Create Full Matrix from a  Sparse Matrix

In [14]:
def make_full_matrix(sparse_matrix, nr_words, doc_idx=0, word_idx=1, cat_idx=2, freq_idx=3):
    """
    From a full matrix from a sparse matrix.
    Return pandas DataFrame
    Keyword arguments:
    sparse_matrix -- numpy array
    nr_words -- size of vocabulary, total number of tokens
    doc_idx -- position of the document id in the sparse matrix
    word_idx -- position of the word id in the sparse matrix
    cat_idx -- position of the label (spam 0, nonspam 1) in the sparse matrix
    freq_idx -- position of the occurence in the sparse matrix
    
    """
    doc_id_names = np.unique(sparse_matrix[:, 0])
    column_names = ['DOC_ID'] + ['CATEGORY'] + list(range(0, VOCAB_SIZE))
    full_matrix = pd.DataFrame(columns=column_names, index=doc_id_names)
    full_matrix.fillna(value=0, inplace=True)
    
    for i in range(sparse_matrix.shape[0]):
        doc_id = sparse_matrix[i][doc_idx]
        word_id = sparse_matrix[i][word_idx]
        label = sparse_matrix[i][cat_idx]
        occurence = sparse_matrix[i][freq_idx]
        
        full_matrix.at[doc_id, 'DOC_ID'] = doc_id
        full_matrix.at[doc_id, 'CATEGORY'] = label
        full_matrix.at[doc_id, word_id] = occurence
        
    full_matrix.set_index('DOC_ID', inplace=True)
    
    return full_matrix

In [15]:
%%time
full_train_data = make_full_matrix(sparse_train_data, VOCAB_SIZE)

Wall time: 13.9 s


In [16]:
full_train_data

CATEGORY  0  1  2  3  4  5  6   7  8  ...  2490  2491  2492  2493  \
DOC_ID                                        ...                           
0              1  0  0  1  2  1  0  0   3  0  ...     0     0     0     0   
1              1  7  1  2  0  1  0  0   1  0  ...     0     0     0     0   
2              1  6  1  1  0  1  0  0   1  0  ...     0     0     0     0   
3              1  6  0  0  2  4  0  3  13  0  ...     0     0     0     0   
4              1  5  1  2  0  1  0  0   1  0  ...     0     0     0     0   
...          ... .. .. .. .. .. .. ..  .. ..  ...   ...   ...   ...   ...   
5789           0  3  1  0  1  0  0  0   1  0  ...     0     0     0     0   
5790           0  1  1  1  0  0  0  1   0  0  ...     0     0     0     0   
5791           0  3  1  0  1  1  0  0   0  1  ...     0     0     0     0   
5794           0  1  1  1  0  0  1  2   0  0  ...     0     0     0     0   
5795           0  3  4  2  0  5  0  3   0  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
0          0     0     0     0     0     0  
1          0     0     0     0     0     0  
2          0     0     0     0     0     0  
3          0     0     0     0     0     0  
4          0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...  
5789       0     0     0     0     0     0  
5790       0     0     0     0     0     0  
5791       0     0     0     0     0     0  
5794       0     0     0     0     0     0  
5795       0     0     0     0     0     0  

[4015 rows x 2501 columns]

# Training Naive Bayes Model

### Calculating the probability of Spam

In [17]:
prob_spam = full_train_data.CATEGORY.sum()/full_train_data.CATEGORY.size

In [18]:
print('prob of spam is', prob_spam)

prob of spam is 0.31133250311332505


### Total number of Words/Tokens

In [19]:
# full_train_data.drop('CATEGORY', axis=1)
full_train_features = full_train_data.loc[:, full_train_data.columns != 'CATEGORY']
full_train_features

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
0          0     0     1     2     1     0     0     3     0     0  ...     0   
1          7     1     2     0     1     0     0     1     0     0  ...     0   
2          6     1     1     0     1     0     0     1     0     0  ...     0   
3          6     0     0     2     4     0     3    13     0     0  ...     0   
4          5     1     2     0     1     0     0     1     0     0  ...     0   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
5789       3     1     0     1     0     0     0     1     0     0  ...     0   
5790       1     1     1     0     0     0     1     0     0     0  ...     0   
5791       3     1     0     1     1     0     0     0     1     0  ...     0   
5794       1     1     1     0     0     1     2     0     0     1  ...     0   
5795       3     4     2     0     5     0     3     0     0     4  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
0          0     0     0     0     0     0     0     0     0  
1          0     0     0     0     0     0     0     0     0  
2          0     0     0     0     0     0     0     0     0  
3          0     0     0     0     0     0     0     0     0  
4          0     0     0     0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
5789       0     0     0     0     0     0     0     0     0  
5790       0     0     0     0     0     0     0     0     0  
5791       0     0     0     0     0     0     0     0     0  
5794       0     0     0     0     0     0     0     0     0  
5795       0     0     0     0     0     0     0     0     0  

[4015 rows x 2500 columns]

In [20]:
email_lengths = full_train_features.sum(axis=1)
total_wc = email_lengths.sum() #total word count
total_wc

431002

### Number of Tokens in Spam & Ham Emails

In [21]:
spam_lengths = email_lengths[full_train_data.CATEGORY == 1]
spam_lengths.shape

(1250,)

In [22]:
spam_wc = spam_lengths.sum() #spam word count
spam_wc

178661

In [23]:
ham_lengths = email_lengths[full_train_data.CATEGORY == 0]
ham_lengths

DOC_ID
1896     82
1898    112
1899     66
1900     49
1901     34
       ... 
5789     18
5790     72
5791     46
5794     57
5795    264
Length: 2765, dtype: int64

In [24]:
ham_wc = ham_lengths.sum() #non-spam word count
ham_wc

252341

### Summing the Tokens Occuring in Spam

In [25]:
full_train_features.shape

(4015, 2500)

In [26]:
train_spam_tokens = full_train_features.loc[full_train_data.CATEGORY == 1]
train_spam_tokens.shape

(1250, 2500)

In [27]:
summed_spam_token = train_spam_tokens.sum(axis = 0) + 1 #laplace smoothing
summed_spam_token

0       2177
1        936
2       1220
3       2026
4       1211
        ... 
2495      19
2496       1
2497      18
2498      25
2499       1
Length: 2500, dtype: int64

### Summing the Tokens Occuring in Non-Spam

In [28]:
train_ham_tokens = full_train_features.loc[full_train_data.CATEGORY == 0]
train_ham_tokens

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
1896       1     2     1     0     1     1     2     0     1     1  ...     0   
1898       2     1     0     1     1     0     2     1     0     0  ...     0   
1899       2     1     1     0     0     1     1     0     1     0  ...     0   
1900       3     4     0     1     0     0     1     1     1     1  ...     0   
1901       2     2     0     1     0     0     1     1     0     0  ...     0   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
5789       3     1     0     1     0     0     0     1     0     0  ...     0   
5790       1     1     1     0     0     0     1     0     0     0  ...     0   
5791       3     1     0     1     1     0     0     0     1     0  ...     0   
5794       1     1     1     0     0     1     2     0     0     1  ...     0   
5795       3     4     2     0     5     0     3     0     0     4  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
1896       0     0     0     0     0     0     0     0     0  
1898       0     0     0     0     0     0     0     0     0  
1899       0     0     0     0     0     0     0     0     0  
1900       0     0     0     0     0     0     0     0     0  
1901       0     0     0     0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
5789       0     0     0     0     0     0     0     0     0  
5790       0     0     0     0     0     0     0     0     0  
5791       0     0     0     0     0     0     0     0     0  
5794       0     0     0     0     0     0     0     0     0  
5795       0     0     0     0     0     0     0     0     0  

[2765 rows x 2500 columns]

In [29]:
summed_ham_tokens = train_ham_tokens.sum(axis=0) + 1
summed_ham_tokens

0       5483
1       2588
2       2044
3        938
4       1611
        ... 
2495      16
2496      31
2497      14
2498       3
2499      36
Length: 2500, dtype: int64

### P(Token | Spam) - Prorbability that a Token Occurs given the Email is Spam

In [30]:
prob_tokens_spam = summed_spam_token / (spam_wc + VOCAB_SIZE) 
# phải cộng VOCAB_SIZE vì ta thêm 1 vào mỗi spam token nên wc phải tăng thêm 


In [31]:
prob_tokens_spam.sum()

1.0

### P(Token | Ham) - Prorbability that a Token Occurs given the Email is Non-Spam

In [32]:
prob_tokens_ham = summed_ham_tokens / (ham_wc + VOCAB_SIZE)

In [33]:
prob_tokens_ham.sum()

1.0

### P(Token) - Probability that Token Occurs

In [34]:
prob_tokens_all = full_train_features.sum(axis=0) / total_wc

In [35]:
prob_tokens_all.sum()

1.0

# Save the Trained Model

In [36]:
np.savetxt(TOKEN_SPAM_PROB_FILE, prob_tokens_spam)
np.savetxt(TOKEN_HAM_PROB_FILE, prob_tokens_ham)
np.savetxt(TOKEN_ALL_PROB_FILE, prob_tokens_all)

# Prepare Test Data

In [37]:
%%time
full_test_data = make_full_matrix(sparse_test_data, VOCAB_SIZE)

Wall time: 5.86 s


In [38]:
test_target = full_test_data.CATEGORY
test_features = full_test_data.drop('CATEGORY', axis=1)
# full_test_data.loc[:, full_test_data.columns != 'CATEGORY']

In [39]:
np.savetxt(TEST_FEATURES_FILE, test_features)
np.savetxt(TEST_TARGET_FILE, test_target)